version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    volumes:
      - "mc:/data"
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      MODE: "survival"
      VERSION: 1.12

volumes:
  mc:
  rcon:
